# Generated by Django 2.0.6 on 2018-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_text', models.CharField(max_length=200, verbose_name='Menu Option')),
            ],
            options={
                'verbose_name': 'Menu Option',
                'verbose_name_plural': 'Menu Options',
            },
        ),
    ]
