# Generated by Django 2.0.6 on 2018-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_homemenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemenu',
            name='menu_text',
            field=models.CharField(max_length=200, verbose_name='Menu Options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
