# Generated by Django 2.0.6 on 2018-06-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180614_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='homemenu',
            options={'verbose_name': 'Menu Option', 'verbose_name_plural': 'Menu Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='menu_text',
            field=models.CharField(max_length=200, verbose_name='Menu Option'),
        ),
    ]
