# Generated by Django 2.0.6 on 2018-06-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180614_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeMenu',
        ),
    ]
